name: Deployment

on:
  push:
    branches:
      - TEST
      - LIVE

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Show current directory
      run: pwd
    - name: Show environment variables
      run: printenv
    - name: ls
      run: ls -la $GITHUB_WORKSPACE
    - name: ls deploy
      run: ls -la $GITHUB_WORKSPACE/deploy
    - run: bash $GITHUB_WORKSPACE/deploy/action.sh
      name: Run deployment script action.sh
      env:
        APPRISE_URL: ${{ secrets.APPRISE_URL }}
        SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
