name: Deployment

on:
  push:
    branches:
      - TEST
      - LIVE

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/bin/sh@master
      with:
        args: ["bash $GITHUB_WORKSPACE/deploy/action.sh"]
      env:
        APPRISE_URL: ${{ secrets.APPRISE_URL }}
        SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
